[project]
name = "vulpix"
dynamic = ["version", "description"]

[project.scripts]
vulpix = "vulpix.__main__:main"

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/vulpix/__init__.py"

[tool.pyright]
include = ["src"]
exclude = ["**/__pycache__"]
defineConstant = { DEBUG = true }
reportMissingImports = "error"
pythonVersion = "3.14"
pythonPlatform = "All"
