import importlib
import sys
from abc import ABC, abstractmethod
from dataclasses import astuple, dataclass, field

from vulpix.core.manager_tasks import *
from vulpix.core.managers import *
from vulpix.core.tasks import task_function


class InvalidPackage(Exception):
    """thrown when a package is not supported by the manager"""

    def __init__(self, package: str, manager: str):
        self.package = package
        self.manager = manager

    def __str__(self):
        return f"invalid package '{self.package}' for '{self.manager}' manager"


@dataclass
class PackageDiff:
    to_install: list[str] = field(default_factory=list)
    to_update: list[str] = field(default_factory=list)
    to_reinstall: list[str] = field(default_factory=list)
    to_uninstall: list[str] = field(default_factory=list)

    def is_empty(self) -> bool:
        return all(len(v) == 0 for v in astuple(self))


class PackageManager(ABC):
    """base class that all package managers (including external plugins) must inherit from"""

    @abstractmethod
    def check_packages(self, packages: list[str]) -> None:
        """:raises InvalidPackage: if a package is not supported"""

    @abstractmethod
    def get_package_diff(self, blueprint_packages: list[str]) -> PackageDiff:
        """
        loads PackageDiff with the changes necessary for the currently package state to reach the
        the blueprint's target state.
        """

    @abstractmethod
    @task_function
    def apply_changes(self, diff: PackageDiff, **_) -> None:
        """
        applies the package changes generated by get_package_diff(), after any filtering by the
        user.

        this must be a task_function; it should use the `logger` kwarg for logging, and it has
        the option to spawn more tasks with the `queue` kwarg (like `queue.run_task(...)`).
        """


manager_modules: dict[str, str] = get_manager_modules(namespace=sys.modules[__name__])
manager_cache: dict[str, PackageManager] = {}


def get_manager(name: str) -> PackageManager:
    """
    NOTE: the PackageManager instance of a module is cached and reused when calling this multiple
    times with the same manager. this was done so it doesn't have to reload everything between, for
    example, blueprint validation and package management.
    """

    if name in manager_cache:
        return manager_cache[name]

    if name not in manager_modules:
        raise ManagerUnsupported(name, "cannot find package manager")

    module = importlib.import_module(manager_modules[name])
    manager_instance = get_subclass_export_instance(
        module, "package_manager_class", interface=PackageManager
    )

    manager_cache[name] = manager_instance
    return manager_instance
