import importlib
from abc import ABC, abstractmethod
from dataclasses import dataclass, field

from vulpix.core import VulpixError, tasks

class PackageManager(ABC):
    """base class that all package managers (including external plugins) must inherit from"""

    class ManagerUnsupported(Exception):
        """thrown when manager cannot be used on the current system/user"""
        manager: str
        message: str
        def __init__(self, manager: str, message: str):
            self.manager = manager
            self.message = message

    class InvalidPackage(Exception):
        """thrown when a package is not supported by a manager"""
        package: str
        manager: str
        def __init__(self, package: str, manager: str):
            self.package = package
            self.manager = manager

    @dataclass
    class PackageDiff:
        to_install: list[str] = field(default_factory=list)
        to_update: list[str] = field(default_factory=list)
        to_reinstall: list[str] = field(default_factory=list)
        to_uninstall: list[str] = field(default_factory=list)

    @abstractmethod
    def check_packages(self, packages: list[str]) -> None:
        """:raises InvalidPackage: if a package is not supported"""
        pass

    @abstractmethod
    def get_package_diff(self, blueprint_packages: list[str]) -> PackageDiff:
        """
        loads PackageDiff with the changes necessary for the currently package state to reach the
        the blueprint's target state.
        """
        pass

    @abstractmethod
    @tasks.task_function
    def apply_changes(self, diff: PackageDiff, **_) -> None:
        """applies the package changes generated by get_package_diff(), after any filtering."""
        pass

_package_cache: dict[str, PackageManager] = {}

def get_package_manager(id: str) -> PackageManager:
    """
    imports the corresponding manager module and loads the core functions into a Manager object.

    expects the package manager module to export `package_manager_class` wich should inherit
    the PackageManager base class.

    NOTE: this was done because importing acts as a cache, so we can call get_manager() during
    blueprint validation and again during package management, and it doesn't have to reload
    everything.
    """

    if id in _package_cache:
        return _package_cache[id]

    try:
        module = importlib.import_module(f".{id}", package=__name__)
    except ModuleNotFoundError as e:
        print(e)
        raise PackageManager.ManagerUnsupported(id, "manager does not exist")

    # verify class export
    if not hasattr(module, "package_manager_class"):
        raise PackageManager.ManagerUnsupported("module imported but expected 'package_manager_class' to be exported")
    manager_class = module.package_manager_class
    if not issubclass(manager_class, PackageManager):
        raise PackageManager.ManagerUnsupported("module imported but 'package_manager_class' is not subclass of PackageManager")

    manager_instance = manager_class()
    _package_cache[id] = manager_instance
    return manager_instance
