import sys
import importlib
from abc import ABC, abstractmethod
from dataclasses import dataclass, field

from vulpix.core import VulpixError, tasks
from vulpix.core.managers import *

class InvalidPackage(Exception):
    """thrown when a package is not supported by the manager"""
    package: str
    manager: str
    def __init__(self, package: str, manager: str):
        self.package = package
        self.manager = manager

class PackageManager(ABC):
    """base class that all package managers (including external plugins) must inherit from"""

    @dataclass
    class PackageDiff:
        to_install: list[str] = field(default_factory=list)
        to_update: list[str] = field(default_factory=list)
        to_reinstall: list[str] = field(default_factory=list)
        to_uninstall: list[str] = field(default_factory=list)

    @abstractmethod
    def check_packages(self, packages: list[str]) -> None:
        """:raises InvalidPackage: if a package is not supported"""
        pass

    @abstractmethod
    def get_package_diff(self, blueprint_packages: list[str]) -> PackageDiff:
        """
        loads PackageDiff with the changes necessary for the currently package state to reach the
        the blueprint's target state.
        """
        pass

    @abstractmethod
    @tasks.task_function
    def apply_changes(self, diff: PackageDiff, **_) -> None:
        """
        applies the package changes generated by get_package_diff(), after any filtering by the
        user. this must be a task_function; it should use the `logger` kwarg for logging, and it has
        the option to spawn more tasks with the `queue` kwarg (like `queue.run_task(...)`).
        """
        pass

manager_modules: dict[str, str] = get_manager_modules(namespace=sys.modules[__name__])
manager_cache: dict[str, PackageManager] = {}

def get_manager(name: str) -> PackageManager:
    """
    NOTE: the PackageManager instance of a module is cached and reused when calling this multiple
    times with the same manager. this was done so it doesn't have to reload everything between, for
    example, blueprint validation and package management.
    """

    if name in manager_cache:
        return manager_cache[name]

    if name not in manager_modules:
        raise PackageManager.ManagerUnsupported(name, "cannot find manager")

    module = importlib.import_module(manager_modules[name])
    manager_class = get_subclass_export(module, "package_manager_class", interface=PackageManager)

    manager_instance = manager_class()
    manager_cache[name] = manager_instance
    return manager_instance
